### ISSUE TITLE
linux-hardened-headers should provide linux-headers

### ISSUE THREAD

**Issue by beihempels** [anthraxx/linux-hardened#97]
see title

**Comment by hardfalcon** [comment]
There's two problems with this issue:
1. This is the wrong bug tracker, because your issue is about packaging, not about the actual code.
2. You are misunderstanding what the `linux-hardened-headers` package is actually used for. It is *not* used nor intended to build userland software, but to build out of tree *kernel modules* (for example, using DKMS) specifically for the version of `linux-hardened` and `linux-hardened-headers` that is installed. To build *userland software*, the header files from the `linux-api-headers` package are used.
